# 逻辑运算符的使用
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print('-'*40)
print(8>7 and 6>5)
print(8>7 and 6<5)
print(8<7 and 6/0)
print('-'*40)
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print('-'*40)
print(8>7 or 10/0)
print('-'*40)
print(not True)
print(not False)
print(not (8>7))